In [1]:
#A1

import numpy as np

# Function for the summation unit
def summation_unit(inputs, weights):
    return np.dot(inputs, weights)

# Activation Functions
def step_function(x):
    return 1 if x >= 0 else 0

def bipolar_step_function(x):
    return 1 if x >= 0 else -1

def sigmoid_function(x):
    return 1 / (1 + np.exp(-x))

def tanh_function(x):
    return np.tanh(x)

def relu_function(x):
    return max(0, x)

def leaky_relu_function(x, alpha=0.01):
    return x if x >= 0 else alpha * x

# Error Comparator Unit
def comparator_unit(predicted, actual):
    return predicted - actual


In [2]:
#A2

# Training data for AND Gate
inputs = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
outputs = np.array([0, 0, 0, 1])  # AND Gate outputs
weights = np.array([10, 0.2, -0.75])  # Including bias as weight
learning_rate = 0.05

# Activation function - Step function
def perceptron_training(inputs, outputs, weights, learning_rate, max_epochs=1000, error_threshold=0.002):
    epochs = 0
    errors = []

    while epochs < max_epochs:
        total_error = 0
        for i in range(len(inputs)):
            input_with_bias = np.insert(inputs[i], 0, 1)  # Adding bias input (1)
            summation = summation_unit(input_with_bias, weights)
            prediction = step_function(summation)
            error = comparator_unit(prediction, outputs[i])
            total_error += error ** 2

            # Weight update rule
            weights += learning_rate * error * input_with_bias
        
        errors.append(total_error)
        epochs += 1

        if total_error <= error_threshold:
            break

    return weights, epochs, errors

# Train the perceptron
weights, epochs, errors = perceptron_training(inputs, outputs, weights, learning_rate)

# Print final weights and epochs taken to converge
print(f"Final weights after training: {weights}")
print(f"Number of epochs taken to converge: {epochs}")


Final weights after training: [160.    50.2   49.25]
Number of epochs taken to converge: 1000


In [3]:
#A3

# Function to handle different activation functions
def perceptron_training_with_activation(inputs, outputs, weights, learning_rate, activation_func, max_epochs=1000, error_threshold=0.002):
    epochs = 0
    errors = []

    while epochs < max_epochs:
        total_error = 0
        for i in range(len(inputs)):
            input_with_bias = np.insert(inputs[i], 0, 1)  # Adding bias input (1)
            summation = summation_unit(input_with_bias, weights)
            prediction = activation_func(summation)
            error = comparator_unit(prediction, outputs[i])
            total_error += error ** 2

            # Weight update rule
            weights += learning_rate * error * input_with_bias
        
        errors.append(total_error)
        epochs += 1

        if total_error <= error_threshold:
            break

    return weights, epochs, errors

# Comparing different activation functions
activation_functions = [step_function, bipolar_step_function, sigmoid_function, relu_function]
for func in activation_functions:
    weights, epochs, errors = perceptron_training_with_activation(inputs, outputs, weights, learning_rate, func)
    print(f"Activation Function: {func.__name__}, Epochs: {epochs}")


Activation Function: step_function, Epochs: 1000
Activation Function: bipolar_step_function, Epochs: 1000
Activation Function: sigmoid_function, Epochs: 1000
Activation Function: relu_function, Epochs: 1000


In [4]:
#A4

learning_rates = [0.1 * i for i in range(1, 11)]
for lr in learning_rates:
    weights = np.array([10, 0.2, -0.75])
    weights, epochs, errors = perceptron_training(inputs, outputs, weights, lr)
    print(f"Learning Rate: {lr}, Epochs: {epochs}")


Learning Rate: 0.1, Epochs: 1000
Learning Rate: 0.2, Epochs: 1000
Learning Rate: 0.30000000000000004, Epochs: 1000
Learning Rate: 0.4, Epochs: 1000
Learning Rate: 0.5, Epochs: 1000
Learning Rate: 0.6000000000000001, Epochs: 1000
Learning Rate: 0.7000000000000001, Epochs: 1000
Learning Rate: 0.8, Epochs: 1000
Learning Rate: 0.9, Epochs: 1000
Learning Rate: 1.0, Epochs: 1000


In [5]:
#A5

# XOR Gate training data
inputs_xor = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
outputs_xor = np.array([0, 1, 1, 0])

# Repeat training for XOR gate
weights_xor = np.array([10, 0.2, -0.75])
weights_xor, epochs_xor, errors_xor = perceptron_training(inputs_xor, outputs_xor, weights_xor, learning_rate)

print(f"Final weights for XOR gate: {weights_xor}")
print(f"Number of epochs taken to converge for XOR gate: {epochs_xor}")


Final weights for XOR gate: [110.    50.2   49.25]
Number of epochs taken to converge for XOR gate: 1000


In [6]:
#A6

import pandas as pd
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix

# A6: Load the provided dataset
data = {
    'Customer': ['C_1', 'C_2', 'C_3', 'C_4', 'C_5', 'C_6', 'C_7', 'C_8', 'C_9', 'C_10'],
    'Candies': [20, 16, 27, 19, 24, 22, 15, 18, 21, 16],
    'Mangoes': [6, 3, 6, 1, 4, 1, 4, 4, 1, 2],
    'Milk Packets': [2, 6, 2, 2, 2, 5, 2, 2, 4, 4],
    'Payment': [386, 289, 393, 110, 280, 167, 271, 274, 148, 198],
    'High Value Tx?': ['Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No']
}

# Create a DataFrame from the dataset
df = pd.DataFrame(data)

# Convert 'High Value Tx?' to binary labels: 'Yes' -> 1, 'No' -> 0
df['High Value Tx?'] = df['High Value Tx?'].apply(lambda x: 1 if x == 'Yes' else 0)

# Features and target variable
X = df[['Candies', 'Mangoes', 'Milk Packets']]
y = df['High Value Tx?']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Standardize the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Initialize the MLPClassifier
mlp = MLPClassifier(hidden_layer_sizes=(10,), activation='logistic', solver='adam', learning_rate_init=0.01, max_iter=1000, random_state=42)

# Train the model
mlp.fit(X_train_scaled, y_train)

# Predict on the test data
y_pred = mlp.predict(X_test_scaled)

# Evaluate the model
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# Display the model weights
print("\nMLPClassifier Weights:")
for i, layer_weights in enumerate(mlp.coefs_):
    print(f"Layer {i + 1} weights:")
    print(layer_weights)



Confusion Matrix:
[[2 0]
 [1 0]]

Classification Report:
              precision    recall  f1-score   support

           0       0.67      1.00      0.80         2
           1       0.00      0.00      0.00         1

    accuracy                           0.67         3
   macro avg       0.33      0.50      0.40         3
weighted avg       0.44      0.67      0.53         3


MLPClassifier Weights:
Layer 1 weights:
[[ 0.08768621 -0.14575011 -0.18549134  0.20989438  0.08244054  0.04899746
   0.0159367   0.00442608  0.02987509  0.01071554]
 [-1.83276218  2.04000055 -1.01081588  1.14206346 -1.89555611  1.38788268
  -1.93214808  1.73295724  1.61591548 -1.65881009]
 [ 0.96047103 -1.29553127  0.61203513 -0.84758868  0.9909088  -0.77305325
   0.8599837  -1.00013628 -0.891341    0.66155013]]
Layer 2 weights:
[[-1.48441261]
 [ 1.11669674]
 [-0.88771983]
 [ 1.44586497]
 [-1.31996287]
 [ 1.50486386]
 [-1.3326076 ]
 [ 1.27426457]
 [ 1.30293431]
 [-1.19466451]]


C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [7]:
#A7

import pandas as pd
import numpy as np
from sklearn.linear_model import Perceptron
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report

# Load the provided dataset into a DataFrame
data = {
    'Customer': ['C_1', 'C_2', 'C_3', 'C_4', 'C_5', 'C_6', 'C_7', 'C_8', 'C_9', 'C_10'],
    'Candies': [20, 16, 27, 19, 24, 22, 15, 18, 21, 16],
    'Mangoes': [6, 3, 6, 1, 4, 1, 4, 4, 1, 2],
    'Milk Packets': [2, 6, 2, 2, 2, 5, 2, 2, 4, 4],
    'Payment': [386, 289, 393, 110, 280, 167, 271, 274, 148, 198],
    'High Value Tx?': ['Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No']
}

# Create a DataFrame from the dataset
df = pd.DataFrame(data)

# Convert 'High Value Tx?' to binary labels: 'Yes' -> 1, 'No' -> 0
df['High Value Tx?'] = df['High Value Tx?'].apply(lambda x: 1 if x == 'Yes' else 0)

# Features and target variable
features = df[['Candies', 'Mangoes', 'Milk Packets']].values
target = df['High Value Tx?'].values

# Standardize the features
scaler = StandardScaler()
features_scaled = scaler.fit_transform(features)

# Function to calculate weights using the pseudo-inverse method
def pseudo_inverse_method(X, y):
    X_bias = np.hstack([np.ones((X.shape[0], 1)), X])  # Add a bias term
    weights_pseudo_inverse = np.linalg.pinv(X_bias).dot(y)
    return weights_pseudo_inverse

# Calculate weights using pseudo-inverse method
weights_pseudo_inverse = pseudo_inverse_method(features_scaled, target)
print(f"Weights obtained using pseudo-inverse method: {weights_pseudo_inverse}")

# Using Perceptron model for comparison
perceptron_model = Perceptron(max_iter=1000, random_state=42)
perceptron_model.fit(features_scaled, target)
perceptron_weights = np.hstack([perceptron_model.intercept_, perceptron_model.coef_[0]])
print(f"Perceptron Weights: {perceptron_weights}")

# Predict and evaluate using perceptron model
predictions = perceptron_model.predict(features_scaled)
print("\nConfusion Matrix (Perceptron):")
print(confusion_matrix(target, predictions))
print("\nClassification Report (Perceptron):")
print(classification_report(target, predictions))



Weights obtained using pseudo-inverse method: [ 0.6        -0.08498457  0.47791444  0.05388368]
Perceptron Weights: [1.         0.05513178 2.61861468 0.62254302]

Confusion Matrix (Perceptron):
[[4 0]
 [0 6]]

Classification Report (Perceptron):
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         4
           1       1.00      1.00      1.00         6

    accuracy                           1.00        10
   macro avg       1.00      1.00      1.00        10
weighted avg       1.00      1.00      1.00        10



In [8]:
#A8

# A8: Neural Network with Backpropagation

# Initialize weights for the neural network
weights_hidden = np.random.rand(3, 2)  # Weights for 2 neurons in the hidden layer (including bias)
weights_output = np.random.rand(3)  # Weights for the output layer (including bias)
learning_rate = 0.05

# Sigmoid Activation function and its derivative
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Backpropagation algorithm for a single hidden layer neural network
def backpropagation_and_gate(inputs, outputs, weights_hidden, weights_output, learning_rate, max_epochs=1000, error_threshold=0.002):
    epochs = 0
    errors = []

    for epoch in range(max_epochs):
        total_error = 0
        for i in range(len(inputs)):
            # Forward pass
            input_with_bias = np.insert(inputs[i], 0, 1)  # Adding bias input (1)
            hidden_layer_input = np.dot(input_with_bias, weights_hidden)
            hidden_layer_output = sigmoid(hidden_layer_input)

            hidden_output_with_bias = np.insert(hidden_layer_output, 0, 1)  # Adding bias for hidden to output layer
            final_input = np.dot(hidden_output_with_bias, weights_output)
            final_output = sigmoid(final_input)

            # Calculate error
            error = comparator_unit(final_output, outputs[i])
            total_error += error ** 2

            # Backward pass (Error Backpropagation)
            delta_output = error * sigmoid_derivative(final_output)
            delta_hidden = delta_output * weights_output[1:] * sigmoid_derivative(hidden_layer_output)

            # Update weights
            weights_output += learning_rate * delta_output * hidden_output_with_bias
            weights_hidden += learning_rate * np.outer(input_with_bias, delta_hidden)

        errors.append(total_error)
        epochs += 1

        if total_error <= error_threshold:
            break

    return weights_hidden, weights_output, epochs, errors

# Train the neural network using backpropagation for AND gate
weights_hidden, weights_output, epochs, errors = backpropagation_and_gate(inputs, outputs, weights_hidden, weights_output, learning_rate)

# Print final weights and epochs taken to converge
print(f"Final hidden weights after training: {weights_hidden}")
print(f"Final output weights after training: {weights_output}")
print(f"Number of epochs taken to converge: {epochs}")


Final hidden weights after training: [[1.10326312 0.6853954 ]
 [0.39700209 0.38209832]
 [0.45966742 0.75104245]]
Final output weights after training: [2.7579924  1.91032374 2.07692508]
Number of epochs taken to converge: 1000


In [9]:
import numpy as np

# Sigmoid activation function and its derivative
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Backpropagation function for XOR gate
def backpropagation_xor(inputs, outputs, weights_hidden, weights_output, learning_rate, epochs=10000):
    # Initialize error tracking
    errors = []
    for epoch in range(epochs):
        # Forward pass
        hidden_input = np.dot(inputs, weights_hidden)
        hidden_output = sigmoid(hidden_input)

        final_input = np.dot(hidden_output, weights_output)
        final_output = sigmoid(final_input)

        # Calculate error (difference between expected and predicted outputs)
        error = outputs - final_output
        errors.append(np.mean(np.abs(error)))

        # Backpropagation
        output_delta = error * sigmoid_derivative(final_output)
        hidden_error = output_delta.dot(weights_output.T)
        hidden_delta = hidden_error * sigmoid_derivative(hidden_output)

        # Update weights
        weights_output += hidden_output.T.dot(output_delta) * learning_rate
        weights_hidden += inputs.T.dot(hidden_delta) * learning_rate

    return weights_hidden, weights_output, epoch, errors

# XOR gate training data
inputs_xor = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
outputs_xor = np.array([[0], [1], [1], [0]])

# Initialize weights (randomly)
np.random.seed(42)  # Set seed for reproducibility
weights_hidden = np.random.uniform(size=(2, 2))  # 2 input nodes, 2 hidden nodes
weights_output = np.random.uniform(size=(2, 1))  # 2 hidden nodes, 1 output node

# Parameters
learning_rate = 0.5

# Train the neural network using backpropagation for XOR gate
weights_hidden_xor, weights_output_xor, epochs_xor, errors_xor = backpropagation_xor(
    inputs_xor, outputs_xor, weights_hidden, weights_output, learning_rate
)

# Print final weights and epochs taken to converge
print(f"Final hidden weights after training for XOR gate:\n{weights_hidden_xor}")
print(f"Final output weights after training for XOR gate:\n{weights_output_xor}")
print(f"Number of epochs taken to converge for XOR gate: {epochs_xor}")

# Test the network with XOR inputs
hidden_output_test = sigmoid(np.dot(inputs_xor, weights_hidden_xor))
final_output_test = sigmoid(np.dot(hidden_output_test, weights_output_xor))
print("\nPredictions after training:")
print(final_output_test)


Final hidden weights after training for XOR gate:
[[0.90571962 7.32475086]
 [0.90572643 7.32731531]]
Final output weights after training for XOR gate:
[[-27.46354604]
 [ 21.74964594]]
Number of epochs taken to converge for XOR gate: 9999

Predictions after training:
[[0.05432317]
 [0.89824588]
 [0.89824604]
 [0.13513664]]


In [10]:
import numpy as np

# Sigmoid activation function and its derivative
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Modified backpropagation function for neural networks with 2 output nodes
def backpropagation_two_output_nodes(inputs, outputs, weights_hidden, weights_output, learning_rate, max_epochs=1000, error_threshold=0.002):
    epochs = 0
    errors = []

    for epoch in range(max_epochs):
        total_error = 0
        for i in range(len(inputs)):
            # Forward pass
            input_with_bias = np.insert(inputs[i], 0, 1)  # Adding bias input (1)
            hidden_layer_input = np.dot(input_with_bias, weights_hidden)
            hidden_layer_output = sigmoid(hidden_layer_input)

            hidden_output_with_bias = np.insert(hidden_layer_output, 0, 1)  # Adding bias for hidden to output layer
            final_input = np.dot(hidden_output_with_bias, weights_output)
            final_output = sigmoid(final_input)

            # Calculate error
            error = outputs[i] - final_output
            total_error += np.sum(error ** 2)

            # Backward pass (Error Backpropagation)
            delta_output = error * sigmoid_derivative(final_output)
            delta_hidden = np.dot(weights_output[1:], delta_output) * sigmoid_derivative(hidden_layer_output)

            # Update weights
            weights_output += learning_rate * np.outer(hidden_output_with_bias, delta_output)
            weights_hidden += learning_rate * np.outer(input_with_bias, delta_hidden)

        errors.append(total_error)
        epochs += 1

        if total_error <= error_threshold:
            break

    return weights_hidden, weights_output, epochs, errors

# AND gate training data with two output nodes (one-hot encoded)
inputs = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])  # Inputs for AND gate
outputs_and_two_nodes = np.array([[1, 0], [1, 0], [1, 0], [0, 1]])  # Mapping 0 to [1, 0] and 1 to [0, 1]

# Initialize weights (randomly)
np.random.seed(42)  # Set seed for reproducibility
weights_hidden = np.random.rand(3, 3)  # 3 input nodes (including bias), 3 hidden nodes
weights_output_two_nodes = np.random.rand(4, 2)  # 3 hidden nodes + 1 bias, 2 output nodes

# Parameters
learning_rate = 0.5

# Train the neural network with 2 output nodes for AND gate
weights_hidden_two_nodes, weights_output_two_nodes, epochs_two_nodes, errors_two_nodes = backpropagation_two_output_nodes(
    inputs, outputs_and_two_nodes, weights_hidden, weights_output_two_nodes, learning_rate
)

# Print final weights and epochs taken to converge
print(f"Final hidden weights after training with 2 output nodes:\n{weights_hidden_two_nodes}")
print(f"Final output weights after training with 2 output nodes:\n{weights_output_two_nodes}")
print(f"Number of epochs taken to converge with 2 output nodes: {epochs_two_nodes}")

# Test the network with AND inputs
for input_data in inputs:
    input_with_bias = np.insert(input_data, 0, 1)  # Add bias to the input
    hidden_layer_output = sigmoid(np.dot(input_with_bias, weights_hidden_two_nodes))
    hidden_output_with_bias = np.insert(hidden_layer_output, 0, 1)  # Add bias to hidden layer output
    final_output = sigmoid(np.dot(hidden_output_with_bias, weights_output_two_nodes))
    print(f"Input: {input_data} => Output: {final_output}")


Final hidden weights after training with 2 output nodes:
[[ 5.22052764 -0.99764253 -1.96946528]
 [-3.84821518  0.8727374   1.75448529]
 [-3.51663571  1.71548308  1.65824936]]
Final output weights after training with 2 output nodes:
[[ 0.59939072 -0.84301645]
 [ 6.25342035 -6.01860498]
 [-2.2602043   2.24773264]
 [-2.75740899  2.98994899]]
Number of epochs taken to converge with 2 output nodes: 1000
Input: [0 0] => Output: [0.9971925  0.00284992]
Input: [0 1] => Output: [0.96102249 0.04069767]
Input: [1 0] => Output: [0.96433906 0.03712207]
Input: [1 1] => Output: [0.05452448 0.94330969]


In [11]:
#A11

from sklearn.neural_network import MLPClassifier

# A11: Using MLPClassifier for AND Gate
mlp_and = MLPClassifier(hidden_layer_sizes=(2,), activation='logistic', learning_rate_init=0.05, max_iter=1000)
mlp_and.fit(inputs, outputs)
print(f"MLPClassifier Weights for AND gate: {mlp_and.coefs_}")

# A11: Using MLPClassifier for XOR Gate
mlp_xor = MLPClassifier(hidden_layer_sizes=(2,), activation='logistic', learning_rate_init=0.05, max_iter=1000)
mlp_xor.fit(inputs_xor, outputs_xor)
print(f"MLPClassifier Weights for XOR gate: {mlp_xor.coefs_}")


MLPClassifier Weights for AND gate: [array([[-4.66439058, -4.70971052],
       [-4.70187354, -4.6722469 ]]), array([[-5.52916835],
       [-4.94161041]])]
MLPClassifier Weights for XOR gate: [array([[-7.21792739, -6.93529282],
       [-4.67000142,  4.70247249]]), array([[-5.92964435],
       [ 6.08290793]])]


C:\ProgramData\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1102: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
